services:
  dozzle:
    env_file:
      - .env
    environment:
      DOZZLE_BASE: /admin/dozzle
      DOZZLE_KEY: ${DOZZLE_KEY}
      DOZZLE_USERNAME: ${DOZZLE_USERNAME}
      DOZZLE_PASSWORD: ${DOZZLE_PASSWORD}
      DOZZLE_NO_ANALYTICS: true
    image: amir20/dozzle:${TAG_DOZZLE}
    restart: ${RESTART}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    command: ['postgres', '-c', 'log_statement=all']
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_BASENAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    image: postgres:${TAG_POSTGRES}
    restart: ${RESTART}
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    image: adminer:${TAG_ADMINER}
    restart: ${RESTART}

  server:
    build:
      args:
        tag: ${TAG_NODE_SERVER}
      context: ./server
      target: production
    command: node dist/main
    depends_on:
      - postgres
    env_file:
      - .env
    restart: ${RESTART}
    volumes:
      - temp:/home/node/app/temp
      - storage:/home/node/app/storage

  client:
    build:
      args:
        tag: ${TAG_NODE_CLIENT}
      context: ./client
      target: production
    command: npm run start
    depends_on:
      - server
    env_file:
      - .env
    restart: ${RESTART}

  nginx:
    env_file:
      - .env
    depends_on:
      - dozzle
      - adminer
      - server
    image: nginx:${TAG_NGINX}
    ports:
      - ${PORT_HTTP}:80
      - ${PORT_HTTPS}:443
    restart: ${RESTART}
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./nginx/http.conf
        target: /etc/nginx/templates/default.conf.template
        read_only: true
      - type: bind
        source: ./nginx/https.conf
        target: /etc/nginx/templates/https.conf.template
        read_only: true
      - type: bind
        source: ./nginx/ssl.crt
        target: /etc/nginx/ssl.crt
        read_only: true
      - type: bind
        source: ./nginx/ssl.key
        target: /etc/nginx/ssl.key
        read_only: true

volumes:
  postgres:
    driver: local
    external: false
  temp:
    driver: local
    external: false
  storage:
    driver: local
    external: false
