export interface EditInterface {
  link?: string | undefined;
  token?: string | undefined;
  url?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  header?: string | undefined;
  content?: string | undefined;
  subFolder?: string | undefined;
  tinyName?: string | undefined;
  tinyAlt?: string | undefined;
  tinyTitle?: string | undefined;
  smallName?: string | undefined;
  smallAlt?: string | undefined;
  smallTitle?: string | undefined;
  bigName?: string | undefined;
  bigAlt?: string | undefined;
  bigTitle?: string | undefined;
  active?: boolean | undefined;
}
